import {createTFPlot} from './tf-plot.js';
import {decodeWav,encodeWav} from './dsp.js';
const $=s=>document.querySelector(s),COLORS=['#9ab5b4','#a2eccb','#e5c391','#9dbdf0'];
const labels=['Speech · LibriTTS / other','Speech · AISHELL-1','Voice / human sounds','Animals','Music / instruments','Environment / other'];
const state={tab:'demo',input:null,requestId:0,inputVersion:0,worker:null,busy:false,recording:null,results:[],routes:null,timing:null,manifest:null,clipStart:0,phase:'idle',replayTimer:null};
let context,transport=null,raf=0,playbackGain=1;
const ctx=()=>context??=new AudioContext();
const fmt=t=>`${Math.floor(t/60)}:${(t%60).toFixed(1).padStart(4,'0')}`;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(text){$('#status').textContent=text;}
function showError(text){$('#error').textContent=text;$('#error').hidden=false;}
function clearError(){$('#error').hidden=true;}
function elapsed(){return transport?(transport.playing?Math.min(transport.track.samples.length/transport.track.sampleRate,transport.offset+context.currentTime-transport.started):transport.offset):0;}
function stopPlayback(reset=false){if(transport){const current=elapsed();transport.source?.stop();transport.source?.disconnect();transport.gain?.disconnect();transport.source=null;transport.playing=false;transport.offset=reset?0:current;}cancelAnimationFrame(raf);drawPlayers();}
function playTrack(track){const current=transport?.track.group===track.group?elapsed():0;stopPlayback();const ac=ctx();ac.resume().catch(()=>{});const source=ac.createBufferSource(),gain=ac.createGain(),buffer=ac.createBuffer(1,track.samples.length,track.sampleRate);buffer.copyToChannel(track.samples,0);source.buffer=buffer;source.connect(gain);gain.connect(ac.destination);gain.gain.value=track.volume*(track.group==='result'?playbackGain:1);const duration=track.samples.length/track.sampleRate,offset=current>=duration-.02?0:current;transport={track,source,gain,offset,started:ac.currentTime,playing:true};source.onended=()=>{if(transport?.source===source){transport.playing=false;transport.offset=0;source.disconnect();gain.disconnect();drawPlayers();}};source.start(0,offset);animate();}
function animate(){drawPlayers();if(transport?.playing)raf=requestAnimationFrame(animate);}
function drawPlayers(){const time=elapsed();for(const el of document.querySelectorAll('.audio-track')){const track=el._track;if(!track)continue;const pos=transport?.track.group===track.group?time:0,active=transport?.track===track&&transport.playing;el.querySelector('.play-button').textContent=active?'Ⅱ':'▶';el.querySelector('.play-button').setAttribute('aria-label',`${active?'Pause ':'Play '}${track.name}`);el.querySelector('.track-time').textContent=`${fmt(pos)} / ${fmt(track.samples.length/track.sampleRate)}`;el.querySelector('canvas').setAttribute('aria-valuenow',pos.toFixed(1));drawWave(el.querySelector('canvas'),track,pos);}}
function drawWave(canvas,track,time){const width=Math.max(1,Math.round(canvas.clientWidth*devicePixelRatio)),height=Math.round(56*devicePixelRatio);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const g=canvas.getContext('2d');g.clearRect(0,0,width,height);const bins=Math.max(1,Math.floor(width/(3*devicePixelRatio)));if(track.waveBins!==bins){track.peaks=new Float32Array(bins);for(let b=0;b<bins;b++){const start=Math.floor(b*track.samples.length/bins),end=Math.max(start+1,Math.floor((b+1)*track.samples.length/bins));let peak=0;for(let i=start;i<end;i++)peak=Math.max(peak,Math.abs(track.samples[i]));track.peaks[b]=peak;}track.waveBins=bins;}const peak=Math.max(.02,...track.peaks),progress=time*track.sampleRate/track.samples.length;for(let b=0;b<bins;b++){const h=Math.max(1,track.peaks[b]/peak*(height-8*devicePixelRatio));g.fillStyle=b/bins<progress?track.color:track.color+'6b';g.fillRect(b*width/bins,(height-h)/2,Math.max(1,width/bins-devicePixelRatio),h);}if(progress>0){g.fillStyle=track.color;g.fillRect(progress*width,0,devicePixelRatio,height);}}
function trackElement(track,download=true){const el=document.createElement('div');el.className='audio-track';el._track=track;el.innerHTML=`<div class="track-name"><span class="track-color" style="background:${track.color}"></span>${escape(track.name)}</div><div class="wave-wrap"><canvas class="wave" role="slider" tabindex="0" aria-label="${escape(track.name)} playback position" aria-valuemin="0" aria-valuemax="${track.samples.length/track.sampleRate}" aria-valuenow="0"></canvas><div class="track-controls"><button class="play-button" aria-label="Play ${escape(track.name)}">▶</button><span class="track-time"></span><input type="range" min="0" max="1" step=".05" value="1" aria-label="${escape(track.name)} volume"></div></div>${download?'<button class="download" title="Download original float WAV" aria-label="Download '+escape(track.name)+'">↓</button>':''}`;
el.querySelector('.play-button').onclick=()=>{if(transport?.track===track&&transport.playing)stopPlayback();else playTrack(track);};const seek=t=>{const wasPlaying=transport?.playing;stopPlayback();transport={track,offset:Math.max(0,Math.min(track.samples.length/track.sampleRate,t)),playing:false};if(wasPlaying)playTrack(track);else drawPlayers();};const canvas=el.querySelector('canvas');canvas.onclick=e=>seek((e.clientX-canvas.getBoundingClientRect().left)/canvas.clientWidth*track.samples.length/track.sampleRate);canvas.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();seek(elapsed()+(e.key==='ArrowRight'?1:-1));}if(e.key===' '){e.preventDefault();el.querySelector('.play-button').click();}};el.querySelector('input').oninput=e=>{track.volume=Number(e.target.value);if(transport?.track===track&&transport.gain)transport.gain.gain.value=track.volume*(track.group==='result'?playbackGain:1);};if(download)el.querySelector('.download').onclick=()=>{const blob=new Blob([encodeWav(track.samples,track.sampleRate)],{type:'audio/wav'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`uss-${track.fileName}.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};return el;}
function resetRouting(){clearInterval(state.replayTimer);state.routes=null;state.results=[];state.timing=null;$('#route-badge').textContent='Ready to run';$('#route-detail').textContent='After separation, select a module to inspect its gate probabilities.';$('#replay').disabled=true;$('#routing-grid').innerHTML='<span></span>'+Array.from({length:6},(_,i)=>`<span class="grid-heading" title="${labels[i]}">E${i}</span>`).join('')+Array.from({length:12},(_,r)=>`<span class="row-heading">L${Math.floor(r/2)+1} · ${r%2?'T':'F'}</span>`+Array.from({length:6},(_,e)=>`<button class="route-cell" data-row="${r}" data-expert="${e}" disabled aria-label="L${Math.floor(r/2)+1} ${r%2?'T':'F'} expert ${e}: Ready to run"></button>`).join('')).join('');$('#results').innerHTML='<div class="empty-result"><span class="empty-icon">≋</span><p>Ready when you are.</p><span>Run separation to listen, compare and download.</span></div>';$('#result-meta').textContent='Original mixture + three sources';resetTechnical();}
function updateSelection(){if(!state.input)return;const duration=state.input.samples.length/state.input.sampleRate,start=Math.min(state.clipStart,Math.max(0,duration-.01)),end=Math.min(duration,start+6);$('#clip-label').textContent=`${start.toFixed(1)}–${end.toFixed(1)} s`;$('#clip-start').max=Math.max(0,duration-6);$('#clip-start').value=start;$('#selection-area').hidden=false;$('#clip-start').disabled=duration<=6||state.busy;$('#input-badge').textContent=`${duration.toFixed(1)} s · ${state.input.sampleRate/1000} kHz`;}
function setInput(input){if(!input.samples.length)throw new Error('The audio is empty.');if(input.samples.length/input.sampleRate>300.001)throw new Error('Please select audio no longer than 5 minutes.');cancelInference(false);stopPlayback(true);state.input=input;state.clipStart=0;state.inputVersion++;resetRouting();$('#input-player').replaceChildren(trackElement({...input,name:'Full input audio',fileName:'original-full',group:'input',color:COLORS[0],volume:1},false));$('#run').disabled=false;updateSelection();message(`Loaded ${input.name}. Choose a segment, then separate audio.`);requestAnimationFrame(drawPlayers);}
async function decodeFile(buffer){const wav=decodeWav(buffer);if(wav)return wav;const audio=await ctx().decodeAudioData(buffer.slice(0));if(audio.duration>300)throw new Error('Please select audio no longer than 5 minutes.');const samples=new Float32Array(audio.length);for(let c=0;c<audio.numberOfChannels;c++){const channel=audio.getChannelData(c);for(let i=0;i<samples.length;i++){if(!Number.isFinite(channel[i]))throw new Error('The audio contains invalid data.');samples[i]+=channel[i]/audio.numberOfChannels;}}return {samples,sampleRate:audio.sampleRate,channels:audio.numberOfChannels};}
async function loadDemo(){const version=++state.inputVersion;try{message('Loading demo audio…');const res=await fetch('demos/mixture.wav');if(!res.ok)throw new Error('Could not load the demo audio. Please retry.');const data=await decodeFile(await res.arrayBuffer());if(version!==state.inputVersion)return;setInput({...data,name:'HIVE demo'});}catch(e){if(version===state.inputVersion){showError(e.message);message('Could not load the demo.');}}}
async function upload(file){if(!file)return;clearError();const version=++state.inputVersion;try{if(file.size>50*1024*1024)throw new Error('Files must be 50 MB or smaller.');message('Decoding local audio…');const data=await decodeFile(await file.arrayBuffer());if(version!==state.inputVersion)return;setInput({...data,name:file.name});if(data.channels>1)message(`Loaded ${file.name}. Mixed ${data.channels} channels down to mono.`);}catch(e){if(version===state.inputVersion){showError(e.message||'This audio format could not be decoded.');message('Please select a supported audio file.');}}}
async function selectTab(tab){if(state.recording)await stopRecording();cancelInference(false);state.inputVersion++;state.tab=tab;clearError();for(const button of document.querySelectorAll('[data-tab]')){const selected=button.dataset.tab===tab;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;}const area=$('#source-area');if(tab==='demo'){area.innerHTML='<div class="demo-card"><div class="demo-top"><strong>Bird, flute & male speech</strong><span class="chip">HIVE · 3 MIX</span></div><p>Three distinct sources in one mixture.</p><span class="sample-meta">00022293_sample_00088558 · 16 kHz · 10 s</span></div>';await loadDemo();}else if(tab==='upload'){area.innerHTML='<div class="upload-zone" id="drop-zone"><strong>Drop an audio file here</strong><br><button id="choose-file" class="secondary file-picker" type="button">Choose audio file</button><input hidden id="file" type="file" accept="audio/*,.wav,.flac,.mp3,.m4a" aria-label="Choose a local audio file"><div class="hint">WAV / MP3 / M4A / FLAC, depending on browser support<br>Up to 50 MB · 5 minutes · Files stay on your device</div></div>';$('#choose-file').onclick=()=>$('#file').click();$('#file').onchange=e=>upload(e.target.files[0]);const zone=$('#drop-zone');zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragging');};zone.ondragleave=()=>zone.classList.remove('dragging');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragging');upload(e.dataTransfer.files[0]);};message('Choose a file, or continue with the audio already loaded.');}else{area.innerHTML='<div class="record-zone"><button id="record" class="secondary">● Start recording</button><p id="record-time">Ready to record · Up to 6 seconds</p><meter id="record-level" min="0" max=".4" value="0" aria-label="Microphone input level"></meter><p class="hint">Separate after recording stops. Pause playback while using the microphone.</p></div>';$('#record').onclick=()=>state.recording?stopRecording():startRecording();message('Start recording to request microphone access.');}}
async function startRecording(){clearError();const version=++state.inputVersion;let stream;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone access requires HTTPS or localhost.');cancelInference(false);stopPlayback(true);$('#record').disabled=true;message('Waiting for microphone access…');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(version!==state.inputVersion||state.tab!=='record'){stream.getTracks().forEach(t=>t.stop());return;}const ac=ctx();await ac.resume();await ac.audioWorklet.addModule('recorder-worklet.js');const source=ac.createMediaStreamSource(stream),node=new AudioWorkletNode(ac,'pcm-recorder'),mute=ac.createGain();mute.gain.value=0;source.connect(node);node.connect(mute);mute.connect(ac.destination);let resolve;const done=new Promise(r=>resolve=r),rec={stream,source,node,mute,chunks:[],count:0,resolve,done,started:performance.now(),settings:stream.getAudioTracks()[0].getSettings()};state.recording=rec;node.port.onmessage=({data})=>{if(data.type==='chunk'){rec.chunks.push(new Float32Array(data.samples));rec.count+=data.samples.byteLength/4;if($('#record-level'))$('#record-level').value=data.rms;}else if(data.type==='stopped')finishRecording(rec);};rec.timer=setInterval(()=>{if($('#record-time'))$('#record-time').textContent=`Recording ${Math.min(6,(performance.now()-rec.started)/1000).toFixed(1)} / 6.0 s`;},100);rec.safetyTimer=setTimeout(()=>node.port.postMessage('stop'),6500);$('#record').disabled=false;$('#record').textContent='■ Stop recording';$('#run').disabled=true;message('Recording…');}catch(e){stream?.getTracks().forEach(t=>t.stop());if($('#record'))$('#record').disabled=false;$('#run').disabled=!state.input;const messages={NotAllowedError:'Microphone access was denied. Allow access or upload an audio file.',NotFoundError:'No microphone found. Connect a device and retry.',NotReadableError:'The microphone is unavailable or in use by another app.'};showError(messages[e.name]??e.message);message('Recording did not start.');}}
function finishRecording(rec){if(state.recording!==rec)return;clearInterval(rec.timer);clearTimeout(rec.safetyTimer);rec.stream.getTracks().forEach(t=>t.stop());rec.source.disconnect();rec.node.disconnect();rec.mute.disconnect();state.recording=null;const samples=new Float32Array(rec.count);let offset=0;for(const chunk of rec.chunks){samples.set(chunk,offset);offset+=chunk.length;}if($('#record')){$('#record').textContent='● Record again';$('#record').disabled=false;$('#record-time').textContent=`Recorded ${(samples.length/context.sampleRate).toFixed(1)} s`;}try{if(samples.length/context.sampleRate<.01)throw new Error('Recording is too short. Please record again.');setInput({samples,sampleRate:context.sampleRate,channels:1,name:'Microphone recording'});state.recordSettings=rec.settings;}catch(e){showError(e.message);}rec.resolve();}
async function stopRecording(){const rec=state.recording;if(!rec)return;rec.node.port.postMessage('stop');await rec.done;}
function setBusy(value){state.busy=value;$('#run').disabled=value||!state.input||!!state.recording;$('#cancel').hidden=!value;$('#clip-start').disabled=value||!state.input||state.input.samples.length/state.input.sampleRate<=6;$('#run').innerHTML=value?'Separating…':'Separate audio <span>↗</span>';}
function cancelInference(announce=true){if(!state.busy)return;state.requestId++;state.worker?.terminate();state.worker=null;clearInterval(state.timer);setBusy(false);$('#progress').hidden=true;state.phase='cancelled';if(announce)message('Cancelled. Start again to reinitialize the model.');state.pendingResolve?.({cancelled:true});state.pendingResolve=null;}
async function runInference(){if(state.busy||!state.input||state.recording)return;clearError();stopPlayback(true);resetRouting();setBusy(true);state.phase='loading-model';const id=++state.requestId;state.started=performance.now();state.timer=setInterval(()=>{if(state.phase==='running')message(`Separating audio · ${((performance.now()-state.started)/1000).toFixed(1)} s elapsed. Routing appears when complete.`);},250);state.worker??=new Worker('inference-worker.js',{type:'module'});const worker=state.worker,result=new Promise(resolve=>state.pendingResolve=resolve);worker.onmessage=({data})=>{if(data.id!==state.requestId)return;if(data.type==='phase'){state.phase=data.phase;message(data.message);$('#progress').hidden=false;$('#progress').removeAttribute('value');}else if(data.type==='download'){$('#progress').hidden=false;$('#progress').max=data.total;$('#progress').value=data.loaded;message(`Downloading model ${(data.loaded/1048576).toFixed(1)} / ${(data.total/1048576).toFixed(1)} MB`);}else if(data.type==='notice'){message(data.message);}else if(data.type==='complete'){clearInterval(state.timer);state.phase='complete';setBusy(false);$('#progress').hidden=true;renderResult(data);state.pendingResolve?.({completed:true,timing:data.timing});state.pendingResolve=null;}else if(data.type==='error'){failRun(data.message);}};worker.onerror=e=>{if(worker===state.worker)failRun(e.message||'The inference worker could not start. Reload and retry.');};const sr=state.input.sampleRate,start=Math.floor(state.clipStart*sr),end=Math.min(state.input.samples.length,start+Math.round(6*sr)),clip=state.input.samples.slice(start,end);state.runningClipStart=start/sr;worker.postMessage({type:'run',id,audio:clip.buffer,sampleRate:sr,threads:new URLSearchParams(location.search).get('threads')==='1'?1:undefined},[clip.buffer]);return result;}
function failRun(text){clearInterval(state.timer);state.phase='error';state.worker?.terminate();state.worker=null;setBusy(false);$('#progress').hidden=true;showError(text);message('Separation failed. Resolve the issue and retry.');state.pendingResolve?.({error:text});state.pendingResolve=null;}
function renderResult(data){state.manifest=data.manifest;state.inputSpectrum=new Float32Array(data.inputSpectrum);state.routes=data.routes;state.timing=data.timing;const arrays=[new Float32Array(data.original),...data.sources.map(b=>new Float32Array(b))];let peak=0;for(const a of arrays)for(const v of a)peak=Math.max(peak,Math.abs(v));playbackGain=peak>.98?.98/peak:1;state.results=arrays.map((samples,i)=>({samples,sampleRate:data.sampleRate,name:i===0?'Original mixture':`Source ${i}`,fileName:i===0?'mixture':`source-${i}`,color:COLORS[i],group:'result',volume:1}));$('#results').replaceChildren(...state.results.map(track=>trackElement(track)));$('#result-meta').textContent=`${state.runningClipStart.toFixed(1)}–${(state.runningClipStart+data.length/data.sampleRate).toFixed(1)} s · Synchronized comparison`;message(`Complete · Inference ${(data.timing.inferenceMs/1000).toFixed(2)} s · ${data.timing.threads} CPU threads`);$('#route-badge').textContent='Actual routing';$('#replay').disabled=false;renderRouting();showRow(0);drawPlayers();renderTechnical();renderTF();}
function renderRouting(activeRow=-1){const p=state.routes.event_probs.data,ids=state.routes.event_selected.data;for(const cell of document.querySelectorAll('.route-cell')){const r=Number(cell.dataset.row),e=Number(cell.dataset.expert),value=p[r*6+e];cell.disabled=false;cell.style.background=`color-mix(in srgb, #a2eccb ${Math.max(4,value*100)}%, #23323a)`;cell.classList.toggle('selected',ids[r]===e);cell.classList.toggle('active',activeRow===r&&ids[r]===e);const label=`L${Math.floor(r/2)+1} ${r%2?'T':'F'}, E${e} ${labels[e]}, Gate probability ${(value*100).toFixed(2)}%${ids[r]===e?', selected':''}`;cell.title=label;cell.setAttribute('aria-label',label);cell.onclick=()=>showRow(r);}}
function showRow(r){if(!state.routes)return;const p=state.routes.event_probs.data,selected=state.routes.event_selected.data[r];$('#route-detail').innerHTML=`<strong style="color:var(--text)">L${Math.floor(r/2)+1} · ${r%2?'Time T':'Frequency F'} → E${selected}</strong>`+labels.map((label,e)=>`<div class="prob-row"><span>E${e} · ${escape(label)}</span><div style="flex:1"><div class="prob-bar" style="width:${p[r*6+e]*100}%"></div></div><b>${(p[r*6+e]*100).toFixed(1)}%</b></div>`).join('');renderRouting(r);}
function replay(){if(!state.routes)return;clearInterval(state.replayTimer);$('#route-badge').textContent='Recorded routing replay';let row=0;showRow(row);if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('#route-badge').textContent='Actual routing';return;}state.replayTimer=setInterval(()=>{row++;if(row>=12){clearInterval(state.replayTimer);$('#route-badge').textContent='Actual routing';return;}showRow(row);},450);}
let routingView = 'event';
let tfLayer = 0;
let tfPlot = null;

function selectRoutingView(view, focus = false) {
  routingView = view;
  for (const button of document.querySelectorAll('[data-routing-view]')) {
    const selected = button.dataset.routingView === view;
    button.setAttribute('aria-selected', String(selected));
    button.tabIndex = selected ? 0 : -1;
    if (selected && focus) button.focus();
  }
  $('#event-routing-panel').hidden = view !== 'event';
  $('#tf-routing-panel').hidden = view !== 'tf';
  if (view === 'tf') {
    clearInterval(state.replayTimer);
    $('#route-badge').textContent = state.routes ? 'Actual routing' : 'Ready to run';
  }
}

for (const button of document.querySelectorAll('[data-routing-view]')) {
  button.onclick = () => selectRoutingView(button.dataset.routingView);
  button.onkeydown = event => {
    if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return;
    event.preventDefault();
    const next = event.key === 'Home' ? 'event' : event.key === 'End' ? 'tf' : routingView === 'event' ? 'tf' : 'event';
    selectRoutingView(next, true);
  };
}

function resetTechnical() {
  state.inputSpectrum = null; tfPlot = null; tfLayer = 0;
  $('#technical-body').innerHTML = '<p class="runtime-placeholder">Model and timing details will appear here when separation completes.</p>';
  $('#tf-content').innerHTML = '<div class="tf-empty"><span class="empty-icon">≋</span><strong>Time–frequency routing</strong><p>Run separation to inspect the actual FFN2 expert selections across time frames and frequency bands.</p></div>';
}

function renderTF() {
  const m=state.manifest,container=$('#tf-content');
  container.innerHTML=`<div class="tf-layer-picker" role="group" aria-label="Select transformer layer">${Array.from({length:m.layers},(_,i)=>`<button data-tf-layer="${i}" aria-pressed="${i===tfLayer}">L${i+1}</button>`).join('')}</div>`;
  if(!state.inputSpectrum?.length){container.insertAdjacentHTML('beforeend','<p class="hint">Reload the page and run separation again to load the updated spectrum view.</p>');return;}
  tfPlot=createTFPlot({spectrum:state.inputSpectrum,manifest:m,routes:state.routes,duration:state.results[0].samples.length/m.sampleRate,clipStart:state.runningClipStart});
  container.append(tfPlot.element);
  const select=index=>{tfLayer=index;tfPlot.setLayer(index);for(const b of container.querySelectorAll('[data-tf-layer]'))b.setAttribute('aria-pressed',String(Number(b.dataset.tfLayer)===index));};
  for(const b of container.querySelectorAll('[data-tf-layer]')){
    b.onclick=()=>select(Number(b.dataset.tfLayer));
    b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?m.layers-1:(Number(b.dataset.tfLayer)+(e.key==='ArrowRight'?1:m.layers-1))%m.layers;select(next);container.querySelector(`[data-tf-layer="${next}"]`).focus();}};
  }
  select(tfLayer);
}

function renderTechnical() {
  const t = state.timing, m = state.manifest;
  const seconds = state.results[0].samples.length / state.results[0].sampleRate;
  const metrics = [
    ['Inference', (t.inferenceMs/1000).toFixed(2), 's', 'Network computation', 'inference'],
    ['Total time', (t.totalMs/1000).toFixed(2), 's', 'Load + DSP + inference', 'total'],
    ['Real-time factor', t.rtf.toFixed(2), '×', 'Inference / audio duration', 'rtf'],
    ['CPU threads', String(t.threads), '', 'ONNX Runtime · WASM', 'threads'],
    ['Model size', (t.modelBytes/1048576).toFixed(1), 'MiB', 'FP32 · EMA weights', 'model'],
    ['Audio segment', seconds.toFixed(2), 's', `${(m.sampleRate/1000).toFixed(0)} kHz · ${m.sources} outputs`, 'audio']
  ];
  $('#technical-body').innerHTML = `<dl class="runtime-metrics">${metrics.map(([label,value,unit,help,key])=>`<div class="runtime-metric" data-metric="${key}"><dt>${label}</dt><dd>${value}<small>${unit}</small></dd><dd class="metric-help">${help}</dd></div>`).join('')}</dl><div class="runtime-bottom"><dl class="runtime-stages"><div><dt>Load / initialize</dt><dd>${(t.loadMs/1000).toFixed(3)} s</dd></div><div><dt>Preprocess</dt><dd>${(t.preprocessMs/1000).toFixed(3)} s</dd></div><div><dt>Reconstruct</dt><dd>${(t.postprocessMs/1000).toFixed(3)} s</dd></div></dl><span class="runtime-cache">${t.warm ? 'Session reused' : t.cacheUsed ? 'Model cache hit' : 'Fresh session'}</span></div><p class="runtime-model"><strong>${escape(m.modelId)}</strong><span>${m.layers} layers · ${m.experts} experts / module · ${m.sources} sources · ${m.channels} model channels · ${m.bands} Mel bands</span></p><p class="hint runtime-note">Short clips are right-padded to ${m.maxSamples/m.sampleRate} seconds. WAV downloads preserve the original float output.${playbackGain<1?` Playback uses a shared gain of ${playbackGain.toFixed(3)} to prevent clipping; downloads are unchanged.`:''}</p>`;
}

$('#run').onclick=runInference;$('#cancel').onclick=()=>cancelInference();$('#replay').onclick=replay;$('#clip-start').oninput=e=>{state.clipStart=Number(e.target.value);stopPlayback(true);resetRouting();updateSelection();message('Segment updated. Select Separate audio to run.');};for(const button of document.querySelectorAll('[data-tab]')){button.onclick=()=>selectTab(button.dataset.tab);button.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const buttons=[...document.querySelectorAll('[data-tab]')],i=buttons.indexOf(button),next=buttons[(i+(e.key==='ArrowRight'?1:2))%3];next.focus();selectTab(next.dataset.tab);}};}
$('#clear-cache').onclick=async()=>{try{await caches.delete('uss-model-v1');message('Model cache cleared. The initialized model can still be used.');}catch{showError('Could not clear the cache. Use your browser site-storage settings.');}};window.addEventListener('resize',drawPlayers);window.addEventListener('pagehide',()=>{state.recording?.stream.getTracks().forEach(t=>t.stop());state.worker?.terminate();stopPlayback();clearInterval(state.timer);clearInterval(state.replayTimer);context?.close();});
window.uss={getState:()=>({phase:state.phase,busy:state.busy,input:state.input?{name:state.input.name,sampleRate:state.input.sampleRate,length:state.input.samples.length}:null,timing:state.timing,routes:state.routes,tfLayer,resultCount:state.results.length}),run:runInference,cancel:cancelInference,getOutputSamples:()=>state.results.map(t=>Array.from(t.samples)),selectDemo:()=>selectTab('demo')};
if(document.modelContext?.registerTool){const lifecycle=new AbortController(),register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_separation_state',description:'Read current separation status, timing and expert routing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(Object.keys(input??{}).length)throw new Error('No arguments expected');return window.uss.getState();}});register({name:'run_selected_separation',description:'Run browser CPU separation on selected audio and update visible tracks and routing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(Object.keys(input??{}).length)throw new Error('No arguments expected');if(!state.input||state.busy)throw new Error('Load audio and wait for active operation');return await runInference();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
resetRouting();selectTab('demo');
