/** Mixed-radix FFT supports the checkpoint's exact 960-point transform. */
class FFTPlan {
  constructor(n){this.n=n;if(n===1)return;this.p=[2,3,5].find(p=>n%p===0)??n;this.m=n/this.p;this.child=new FFTPlan(this.m);this.r=new Float64Array(this.p);this.i=new Float64Array(this.p);this.cos=new Float64Array(n*this.p);this.sin=new Float64Array(n*this.p);for(let k=0;k<n;k++)for(let j=0;j<this.p;j++){const a=-2*Math.PI*j*k/n;this.cos[k*this.p+j]=Math.cos(a);this.sin[k*this.p+j]=Math.sin(a);}}
  run(ir,ii,start,stride,or,oi,offset,inverse){if(this.n===1){or[offset]=ir[start];oi[offset]=ii?.[start]??0;return;}const {p,m,n,child,r,i,cos,sin}=this;for(let j=0;j<p;j++)child.run(ir,ii,start+j*stride,stride*p,or,oi,offset+j*m,inverse);for(let k=0;k<m;k++){for(let j=0;j<p;j++){r[j]=or[offset+j*m+k];i[j]=oi[offset+j*m+k];}for(let q=0;q<p;q++){const dest=k+q*m;let re=0,im=0;for(let j=0;j<p;j++){const c=cos[dest*p+j],s=sin[dest*p+j]*(inverse?-1:1);re+=r[j]*c-i[j]*s;im+=r[j]*s+i[j]*c;}or[offset+dest]=re;oi[offset+dest]=im;}}}
}
const FFT_SIZE=960,HOP=480,MAX_SAMPLES=96000,BINS=481,FRAMES=201;
const plan=new FFTPlan(FFT_SIZE),window=Float64Array.from({length:FFT_SIZE},(_,i)=>(1-Math.cos(2*Math.PI*i/FFT_SIZE))/2);
export const AUDIO={sampleRate:16000,maxSamples:MAX_SAMPLES,fftSize:FFT_SIZE,hopLength:HOP,bins:BINS,frames:FRAMES};
export function stft(pcm){if(pcm.length!==MAX_SAMPLES)throw new Error('STFT requires exactly 96000 padded samples');const result=new Float32Array(FRAMES*BINS*2),ir=new Float64Array(FFT_SIZE),or=new Float64Array(FFT_SIZE),oi=new Float64Array(FFT_SIZE);for(let t=0;t<FRAMES;t++){for(let j=0;j<FFT_SIZE;j++){let idx=t*HOP+j-HOP;if(idx<0)idx=-idx;if(idx>=pcm.length)idx=2*pcm.length-2-idx;ir[j]=pcm[idx]*window[j];}plan.run(ir,null,0,1,or,oi,0,false);for(let f=0;f<BINS;f++){result[(t*BINS+f)*2]=or[f];result[(t*BINS+f)*2+1]=oi[f];}}return result;}
export function istft(spectrum,length=MAX_SAMPLES){if(spectrum.length!==FRAMES*BINS*2)throw new Error('Unexpected spectrum dimensions');if(length<1||length>MAX_SAMPLES)throw new Error('Invalid output length');const total=(FRAMES-1)*HOP+FFT_SIZE,out=new Float64Array(total),norm=new Float64Array(total),ir=new Float64Array(FFT_SIZE),ii=new Float64Array(FFT_SIZE),or=new Float64Array(FFT_SIZE),oi=new Float64Array(FFT_SIZE);for(let t=0;t<FRAMES;t++){for(let f=0;f<BINS;f++){ir[f]=spectrum[(t*BINS+f)*2];ii[f]=spectrum[(t*BINS+f)*2+1];}for(let f=BINS;f<FFT_SIZE;f++){ir[f]=ir[FFT_SIZE-f];ii[f]=-ii[FFT_SIZE-f];}plan.run(ir,ii,0,1,or,oi,0,true);for(let j=0;j<FFT_SIZE;j++){out[t*HOP+j]+=or[j]/FFT_SIZE*window[j];norm[t*HOP+j]+=window[j]*window[j];}}const pcm=new Float32Array(length);for(let i=0;i<length;i++)pcm[i]=out[i+HOP]/norm[i+HOP];return pcm;}
/** Windowed-sinc resampling. Anti-alias filter, 64 taps, exact fractional phases. */
export function resample(input,fromRate,toRate=16000){if(!Number.isFinite(fromRate)||fromRate<8000||fromRate>192000)throw new Error('Sample rate must be between 8 and 192 kHz.');if(fromRate===toRate)return input.slice();const count=Math.max(1,Math.round(input.length*toRate/fromRate)),out=new Float32Array(count),ratio=fromRate/toRate,cutoff=Math.min(1,toRate/fromRate)*.94,half=32;const phases=new Map();for(let i=0;i<count;i++){const pos=i*ratio,center=Math.floor(pos),frac=pos-center,key=Math.round(frac*1e8);let weights=phases.get(key);if(!weights){weights=new Float64Array(half*2);let sum=0;for(let j=-half+1;j<=half;j++){const x=j-frac,v=x*cutoff;const sinc=Math.abs(v)<1e-12?1:Math.sin(Math.PI*v)/(Math.PI*v);const hann=.5+.5*Math.cos(Math.PI*x/half);const w=sinc*cutoff*hann;weights[j+half-1]=w;sum+=w;}for(let j=0;j<weights.length;j++)weights[j]/=sum;phases.set(key,weights);}let value=0;for(let j=-half+1;j<=half;j++){const index=Math.max(0,Math.min(input.length-1,center+j));value+=input[index]*weights[j+half-1];}out[i]=value;}return out;}
export function prepareInput(input,sampleRate){const selected=resample(input,sampleRate);const length=Math.min(MAX_SAMPLES,selected.length);if(length<160)throw new Error('Please select at least 0.01 seconds of audio.');const padded=new Float32Array(MAX_SAMPLES);padded.set(selected.subarray(0,length));for(const v of padded)if(!Number.isFinite(v))throw new Error('The audio contains invalid samples.');return {padded,length,selected:selected.slice(0,length)};}
/** Decode WAV without routing an already-16kHz fixture through a device-rate decoder. */
export function decodeWav(arrayBuffer){const view=new DataView(arrayBuffer),tag=(o)=>String.fromCharCode(...new Uint8Array(arrayBuffer,o,4));if(view.byteLength<12||tag(0)!=='RIFF'||tag(8)!=='WAVE')return null;let fmt=null,offset=12,dataStart=0,dataSize=0;while(offset+8<=view.byteLength){const id=tag(offset),size=view.getUint32(offset+4,true),start=offset+8;if(start+size>view.byteLength)throw new Error('The WAV file is incomplete.');if(id==='fmt '){if(size<16)throw new Error('Invalid WAV header.');let format=view.getUint16(start,true);if(format===65534&&size>=40)format=view.getUint16(start+24,true);fmt={format,channels:view.getUint16(start+2,true),sampleRate:view.getUint32(start+4,true),align:view.getUint16(start+12,true),bits:view.getUint16(start+14,true)};}if(id==='data'){dataStart=start;dataSize=size;}offset=start+size+(size%2);}if(!fmt||!dataStart)throw new Error('The WAV file has no audio data.');const {format,channels,sampleRate,align,bits}=fmt;if(![1,3].includes(format))return null;if(channels<1||channels>32||sampleRate<8000||sampleRate>192000||![8,16,24,32,64].includes(bits)||align!==channels*bits/8)throw new Error('Unsupported WAV parameters.');const frames=Math.floor(dataSize/align);if(frames/sampleRate>300)throw new Error('Please select audio no longer than 5 minutes.');const samples=new Float32Array(frames);for(let i=0;i<frames;i++){let v=0;for(let c=0;c<channels;c++){const o=dataStart+i*align+c*bits/8;let x;if(format===3){if(bits===32)x=view.getFloat32(o,true);else if(bits===64)x=view.getFloat64(o,true);else throw new Error('Unsupported float WAV format.');}else if(bits===8)x=(view.getUint8(o)-128)/128;else if(bits===16)x=view.getInt16(o,true)/32768;else if(bits===24){const z=view.getUint8(o)|(view.getUint8(o+1)<<8)|(view.getUint8(o+2)<<16);x=((z<<8)>>8)/8388608;}else if(bits===32)x=view.getInt32(o,true)/2147483648;else throw new Error('Unsupported PCM WAV format.');if(!Number.isFinite(x))throw new Error('The WAV file contains invalid data.');v+=x/channels;}samples[i]=v;}return {samples,sampleRate,channels};}
export function encodeWav(samples,sampleRate=16000,{float=true,gain=1}={}){const size=float?4:2,buffer=new ArrayBuffer(44+samples.length*size),v=new DataView(buffer);const str=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,buffer.byteLength-8,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,float?3:1,true);v.setUint16(22,1,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*size,true);v.setUint16(32,size,true);v.setUint16(34,size*8,true);str(36,'data');v.setUint32(40,samples.length*size,true);for(let i=0;i<samples.length;i++){const x=samples[i]*gain;if(!Number.isFinite(x))throw new Error('The output contains invalid samples.');if(float)v.setFloat32(44+i*size,x,true);else v.setInt16(44+i*size,Math.max(-32768,Math.min(32767,Math.round(x*32768))),true);}return buffer;}
